"""Versioned artifact bundles: package once, load safely anywhere.

An artifact bundle carries an optimized graph kernel together with the
evidence and compatibility metadata a runtime needs to decide whether it may
execute it. Selection is keyed on the captured graph fingerprint and tensor
signatures, never on the model's name, so a runtime integrates this contract
once and gains every future artifact for free.
"""

from __future__ import annotations

from .compat import (
    REASON_ARCHITECTURE_MISMATCH,
    REASON_CUDA_VERSION,
    REASON_DISTRIBUTED_MODE,
    REASON_EVIDENCE_INCOMPLETE,
    REASON_EXECUTION_MODE,
    REASON_FINGERPRINT_MISMATCH,
    REASON_INPUT_SIGNATURE_MISMATCH,
    REASON_MODEL_MISMATCH,
    REASON_NOT_PROMOTED,
    REASON_OUTPUT_SIGNATURE_MISMATCH,
    REASON_REVISION_MISMATCH,
    REASON_TORCH_VERSION,
    REASON_TRITON_VERSION,
    REJECTION_REASONS,
    DispatchRequest,
    MatchResult,
    Rejection,
    RuntimeProfile,
    check_compatibility,
    match_artifact,
)
from .finalizer import (
    FINALIZED_DECISIONS,
    GENERATION_METRIC,
    MEASURED_CLASSIFICATIONS,
    FinalizationResult,
    GenerationOutcome,
    finalize_bundle,
)
from .loader import load_entry_point
from .packager import (
    DEFAULT_PRODUCER,
    build_manifest,
    discover_bundles,
    load_bundles,
    package_artifact,
)
from .types import (
    ANY,
    ARTIFACT_SCHEMA_VERSION,
    DISTRIBUTED_MODES,
    EXECUTION_MODES,
    MANIFEST_FILENAME,
    PROMOTION_DECISIONS,
    ArtifactError,
    ArtifactManifest,
    BenchmarkEvidence,
    CampaignRef,
    Compatibility,
    EntryPoint,
    Evidence,
    FileDigest,
    GenerationEvidence,
    GraphSignature,
    OperationIdentity,
    Promotion,
    TensorSignature,
    VersionRange,
    parse_version,
)
from .validator import describe_bundle, file_sha256, read_manifest, verify_bundle

__all__ = [
    "ANY",
    "ARTIFACT_SCHEMA_VERSION",
    "DEFAULT_PRODUCER",
    "DISTRIBUTED_MODES",
    "EXECUTION_MODES",
    "FINALIZED_DECISIONS",
    "GENERATION_METRIC",
    "MANIFEST_FILENAME",
    "MEASURED_CLASSIFICATIONS",
    "PROMOTION_DECISIONS",
    "REASON_ARCHITECTURE_MISMATCH",
    "REASON_CUDA_VERSION",
    "REASON_DISTRIBUTED_MODE",
    "REASON_EVIDENCE_INCOMPLETE",
    "REASON_EXECUTION_MODE",
    "REASON_FINGERPRINT_MISMATCH",
    "REASON_INPUT_SIGNATURE_MISMATCH",
    "REASON_MODEL_MISMATCH",
    "REASON_NOT_PROMOTED",
    "REASON_OUTPUT_SIGNATURE_MISMATCH",
    "REASON_REVISION_MISMATCH",
    "REASON_TORCH_VERSION",
    "REASON_TRITON_VERSION",
    "REJECTION_REASONS",
    "ArtifactError",
    "ArtifactManifest",
    "BenchmarkEvidence",
    "CampaignRef",
    "Compatibility",
    "DispatchRequest",
    "EntryPoint",
    "Evidence",
    "FileDigest",
    "FinalizationResult",
    "GenerationEvidence",
    "GenerationOutcome",
    "GraphSignature",
    "MatchResult",
    "OperationIdentity",
    "Promotion",
    "Rejection",
    "RuntimeProfile",
    "TensorSignature",
    "VersionRange",
    "build_manifest",
    "check_compatibility",
    "describe_bundle",
    "discover_bundles",
    "file_sha256",
    "finalize_bundle",
    "load_bundles",
    "load_entry_point",
    "match_artifact",
    "package_artifact",
    "parse_version",
    "read_manifest",
    "verify_bundle",
]
