#!/usr/bin/env python3
"""Generate PROVENANCE.md: which files came from upstream and which did not.

MotionKernel is a fork. "How much of this is yours?" is a fair question to ask
of any fork, and the honest answer is a per-file classification against the
exact upstream commit this repository diverged from -- not a percentage in a
README that nobody can check.

Every file is placed in one of three buckets:

``unchanged_upstream``
    Byte-identical to the upstream base commit. Fully covered by the upstream
    copyright in LICENSE.
``modified_descendant``
    Present upstream and since modified here. Derivative work; the upstream
    notice still applies.
``motionkernel_original``
    Added by this project.

Run from the repository root:

    python scripts/provenance_inventory.py --write

Requires the upstream base commit to be reachable. If it is not, fetch it:

    git remote add upstream https://github.com/RightNow-AI/autokernel.git
    git fetch upstream
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from collections import Counter
from pathlib import Path

#: The upstream commit this repository diverged from. Recorded in DOWNSTREAM.md
#: and pinned here so the inventory is reproducible rather than relative to
#: whatever upstream happens to be today.
UPSTREAM_BASE = "7843582"

UPSTREAM_URL = "https://github.com/RightNow-AI/autokernel"

UNCHANGED = "unchanged_upstream"
MODIFIED = "modified_descendant"
ORIGINAL = "motionkernel_original"


class InventoryError(RuntimeError):
    """The inventory could not be built from this checkout."""


def _git(*args: str, root: Path) -> str:
    result = subprocess.run(
        ["git", *args], capture_output=True, text=True, cwd=root, check=False
    )
    if result.returncode != 0:
        raise InventoryError(
            f"git {' '.join(args)} failed: {result.stderr.strip() or 'unknown error'}"
        )
    return result.stdout


def classify(root: Path, base: str = UPSTREAM_BASE) -> dict[str, str]:
    """Map every tracked file in HEAD to its provenance bucket."""
    upstream_files = set(_git("ls-tree", "-r", "--name-only", base, root=root).split())
    # ``ls-files`` rather than ``ls-tree HEAD``: the inventory should describe
    # the tree being committed, including files staged but not yet committed.
    # Reading HEAD would silently omit every file added in the same change that
    # regenerates this document.
    current_files = _git("ls-files", root=root).split()

    changed: dict[str, str] = {}
    for line in _git("diff", "--name-status", base, root=root).splitlines():
        parts = line.split("\t")
        if len(parts) >= 2:
            changed[parts[-1]] = parts[0][0]

    inventory: dict[str, str] = {}
    for path in current_files:
        if path in upstream_files and path not in changed:
            inventory[path] = UNCHANGED
        elif path in upstream_files:
            inventory[path] = MODIFIED
        else:
            inventory[path] = ORIGINAL
    return inventory


def line_counts(root: Path, inventory: dict[str, str], suffix: str = ".py") -> Counter:
    """Line totals per bucket for files matching ``suffix``."""
    totals: Counter = Counter()
    for path, bucket in inventory.items():
        if not path.endswith(suffix):
            continue
        try:
            text = (root / path).read_text(errors="replace")
        except OSError:
            continue
        totals[bucket] += len(text.splitlines())
    return totals


def render(root: Path, inventory: dict[str, str]) -> str:
    files = Counter(inventory.values())
    python = line_counts(root, inventory)
    total_python = sum(python.values()) or 1
    inherited = python[UNCHANGED] + python[MODIFIED]

    lines: list[str] = []
    add = lines.append
    add("# Provenance inventory")
    add("")
    add("<!-- Generated by scripts/provenance_inventory.py. Do not edit by hand. -->")
    add("")
    add(
        "MotionKernel is an independently maintained, MIT-licensed fork of "
        f"[RightNow-AI/AutoKernel]({UPSTREAM_URL}). This file records exactly "
        "what was inherited and what was not, per file, against the upstream "
        f"commit the project diverged from (`{UPSTREAM_BASE}`)."
    )
    add("")
    add(
        "It is generated from the Git history, so it can be regenerated and "
        "checked rather than trusted:"
    )
    add("")
    add("```bash")
    add("python scripts/provenance_inventory.py --check")
    add("```")
    add("")
    add("## Licensing")
    add("")
    add(
        "The upstream MIT license and copyright (`Copyright (c) 2026 RightNow AI`) "
        "are preserved in [LICENSE](LICENSE) and cover every file below that is "
        "not marked *MotionKernel-original*. Files marked *modified descendant* "
        "are derivative works and remain covered by the same notice. No file has "
        "had an upstream copyright header removed."
    )
    add("")
    add("## Summary")
    add("")
    add("| Category | Files | Python lines | Share of Python |")
    add("|---|---:|---:|---:|")
    for bucket, label in (
        (UNCHANGED, "Unchanged from upstream"),
        (MODIFIED, "Modified descendants"),
        (ORIGINAL, "MotionKernel-original"),
    ):
        add(
            f"| {label} | {files[bucket]} | {python[bucket]} | "
            f"{python[bucket] / total_python * 100:.1f}% |"
        )
    add(f"| **Total** | **{sum(files.values())}** | **{sum(python.values())}** | |")
    add("")
    add(
        f"Inherited Python footprint (unchanged plus modified): "
        f"**{inherited / total_python * 100:.1f}%**. The remaining "
        f"{python[ORIGINAL] / total_python * 100:.1f}% -- the artifact format, "
        "graph discovery, spec generation, the workload system, the optimizer "
        "control plane, validation and promotion, the CLI, and the FastVideo "
        "bridge -- is MotionKernel work."
    )
    add("")
    add(
        "The largest remaining visible dependency is the `autokernel` import "
        "namespace, which is a compatibility namespace rather than the product "
        "name. See [docs/NAMESPACE_MIGRATION.md](docs/NAMESPACE_MIGRATION.md)."
    )
    add("")

    add("## Unchanged from upstream")
    add("")
    add(
        "Byte-identical to upstream. These are the inherited single-kernel "
        "research harness, starter kernels, and example models."
    )
    add("")
    for path in sorted(p for p, b in inventory.items() if b == UNCHANGED):
        add(f"- `{path}`")
    add("")

    add("## Modified descendants")
    add("")
    add("Present upstream, modified here. Derivative works.")
    add("")
    for path in sorted(p for p, b in inventory.items() if b == MODIFIED):
        add(f"- `{path}`")
    add("")

    add("## MotionKernel-original")
    add("")
    add(
        f"Added by this project ({files[ORIGINAL]} files). Listed by top-level "
        "location; every file under these paths is original unless named above."
    )
    add("")
    grouped: dict[str, int] = {}
    for path, bucket in inventory.items():
        if bucket != ORIGINAL:
            continue
        head = path.split("/")[0] if "/" in path else path
        grouped[head] = grouped.get(head, 0) + 1
    for head in sorted(grouped):
        add(f"- `{head}` ({grouped[head]} file{'s' if grouped[head] != 1 else ''})")
    add("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--write", action="store_true", help="write PROVENANCE.md")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if PROVENANCE.md is stale",
    )
    parser.add_argument("--base", default=UPSTREAM_BASE, help="upstream base commit")
    args = parser.parse_args(argv)

    root = Path(__file__).resolve().parents[1]
    try:
        inventory = classify(root, args.base)
    except InventoryError as exc:
        print(f"error: {exc}", file=sys.stderr)
        print(
            "hint: the upstream base commit must be reachable; run\n"
            f"  git remote add upstream {UPSTREAM_URL}.git && git fetch upstream",
            file=sys.stderr,
        )
        return 2

    rendered = render(root, inventory)
    target = root / "PROVENANCE.md"

    if args.check:
        current = target.read_text() if target.is_file() else ""
        if current != rendered:
            print("PROVENANCE.md is stale; regenerate with --write", file=sys.stderr)
            return 1
        print("PROVENANCE.md is up to date")
        return 0

    if args.write:
        target.write_text(rendered, encoding="utf-8")
        print(f"wrote {target}")
        return 0

    print(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
